# Generated by Django 5.0 on 2025-10-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('domaine', models.CharField(max_length=100)),
                ('experience', models.TextField(blank=True)),
                ('disponibilite', models.CharField(blank=True, max_length=100)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('lien_linkedin', models.URLField(blank=True)),
            ],
        ),
    ]
