# Generated by Django 5.2.7 on 2025-10-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cv/'),
        ),
        migrations.AddField(
            model_name='consultant',
            name='disponibilite_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='disponibilite',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='experience',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='nom',
            field=models.CharField(max_length=100),
        ),
    ]
